repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: docker-compose run app isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: docker-compose run app black
    types: [python]
  
  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: docker-compose run app flake8
    types: [python]
    exclude: setup.py